PROGRAM HEIGHTTOMOD

!      ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

USE YOMRIP   , ONLY : RTIMST
USE YOMCST   , ONLY : RDAY,RPI
USE YOMLUN   , ONLY : NULNAM, NULOUT

!      -----------------------------------------------------------------
IMPLICIT NONE

CHARACTER(LEN = 17) ::  ASCIIFILENAME
CHARACTER(LEN=18) :: CL_FNAME
CHARACTER(LEN=16) :: CLFRAME(1)
INTEGER(KIND=JPIM), PARAMETER :: JPMXLEV=2000,JNXMAX=9999999
INTEGER(KIND=JPIM) :: I,II,J,N,NT,IREP,INMAX,KGRIDSIZE,JREP
INTEGER(KIND=JPIM) :: IMAXLEV,IMAXTRUNC,IMAXGL,IMAXLON
INTEGER(KIND=JPIM) :: INLATI,INXLON,ITRONC,ITYPTR,ISMAX,INMSMAX,ISPEC2G,ISPEC
INTEGER(KIND=JPIM) :: INLOPA(8),JLEV,IMSMAX,IGPTOTG,IRESOL,IGPTOT
INTEGER(KIND=JPIM),ALLOCATABLE,DIMENSION(:) :: I_REGIONS_EW,I_REGIONS_NS,I_REGIONS
INTEGER(KIND=JPIM),ALLOCATABLE,DIMENSION(:) :: NDATE,NTIME,NSTATID,IDAT,ITIME,IISNAX,IISMAX,ILOEN,IVSETSC
REAL(KIND=JPRB),ALLOCATABLE,DIMENSION(:) :: ZLATO,ZLONO,ZHEIGHTO,ZFFO,ZDDO,ZTTO,ZPPO,ZQQO
REAL(KIND=JPRB),ALLOCATABLE,DIMENSION(:) :: ZUO,ZVO,ZLATLAT,ZLONLON,ZTT,ZQQ,ZPP
REAL(KIND=JPRB),ALLOCATABLE,DIMENSION(:) :: ZFIELD,ZHEIGHT2D,ZREFL2D,ZDIST2D
REAL(KIND=JPRB),ALLOCATABLE,DIMENSION(:) :: ZVALH,ZVBH,ZSINLA,ZSPEC2,ZSPEC1
REAL(KIND=JPRB),ALLOCATABLE,DIMENSION(:,:,:) :: ZGP2,ZGP1,ZGP3,ZGP4,ZGP5
REAL(KIND=JPRB),ALLOCATABLE,DIMENSION(:,:) :: ZSPEC3,ZHEIGHT
REAL(KIND=JPRB) :: ZHOOK_HANDLE,Z_EXWN,Z_EYWN
REAL(KIND=JPRB) :: ZEPS,ZREF,ZHEIGHTMEAN,ZMAXPRES,ZMINPRES,ZPRESSMEAN
REAL(KIND=JPRB), PARAMETER :: ZGASCONST=287._JPRB,ZPREF=101325._JPRB,ZGRAVITY=9.8087_JPRB
DOUBLE PRECISION :: DDIS,DLFAC
LOGICAL :: LLMAP,LLEXIS,LLCOSP
INTEGER(KIND=JPIM) ,ALLOCATABLE,DIMENSION(:) :: IESM0,IDIM0G
INTEGER(KIND=JPIM) :: INGRIB,INBITS,ISTRUN,IPUILA,JN,JM,ISP
#include "echien.h"
#include "einv_trans.h"
#include "setup_trans0.h"
#include "esetup_trans.h"
#include "etrans_inq.h"
#include "abor1.intfb.h"
#include "esperee.intfb.h"
!      -----------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('HEIGHTTOMOD',0,ZHOOK_HANDLE)
!      -----------------------------------------------------------------

!  opening fa files
INMAX=1
CL_FNAME='REFLECTIVITYOBS.fa'
CALL FAITOU(IREP,11,.TRUE.,TRIM(CL_FNAME),'OLD',&
 & .TRUE.,.FALSE.,0,1,INMAX,'CADRE LECTURE   ')
IF (IREP /= 0) then
  write(*,*) 'OPEN FA FILE FAILED',CL_FNAME,' ERROR CODE:',IREP
  CALL ABOR1('OPEN FA FILE FAILED')
ELSE
  write(*,*) 'OPEN FA FILE OK',CL_FNAME,' ERROR CODE:',IREP
ENDIF
INMAX=1
CALL FALIMU(IMAXLEV,IMAXTRUNC,IMAXGL,IMAXLON)
WRITE(*,*)'FALIMU:',IMAXLEV,IMAXTRUNC,IMAXGL,IMAXLON

ALLOCATE(ZFIELD(JNXMAX))
ALLOCATE(ITIME(JNXMAX))
ALLOCATE(IDAT(JNXMAX))
ALLOCATE(ZSINLA(JNXMAX))
ALLOCATE(ZVALH(IMAXLEV))
ALLOCATE(ZVBH(IMAXLEV))

ZEPS =1.E-06_JPRB

CALL ECHIEN('CADRE LECTURE   ',ITYPTR,LLMAP,ITRONC,INLATI,INXLON,INLOPA,&
   & ZSINLA,IMAXLEV,ZREF,ZVALH,ZVBH,1,ZEPS,6)

ISMAX =ITRONC
IMSMAX=ITYPTR
WRITE(*,*)'ITRONC,ITYPTR:',ITRONC,ITYPTR
IGPTOTG=INLATI*INXLON
WRITE(*,*) 'IGPTOTG,IMAXLEV:',IGPTOTG,IMAXLEV
!! WRITE(*,*) 'ZSINLA',ZSINLA
ALLOCATE(IISMAX(0:ISMAX),IISNAX(0:IMSMAX))
CALL ELLIPS(ISMAX,IMSMAX,IISNAX,IISMAX)
ISPEC2G=0
DO J=0,IMSMAX
  ISPEC2G=ISPEC2G+4*(IISNAX(J)+1)
ENDDO



IF(ALLOCATED(I_REGIONS))DEALLOCATE(I_REGIONS)
!! CALL SETUP_TRANS0(KPRINTLEV=1,LDMPOFF=.FALSE.,KMAX_RESOL=1,KPRGPNS=1,KPRGPEW=1,KPRTRW=1)
CALL SETUP_TRANS0(LDMPOFF=.TRUE.,K_REGIONS=I_REGIONS)
IRESOL=-1
ALLOCATE(ILOEN(2*INLATI))
ILOEN(:)=INXLON

Z_EXWN=1.
Z_EYWN=1.
CALL ESETUP_TRANS(KMSMAX=IMSMAX,KSMAX=ISMAX,KDGUX=INLOPA(6),KDGL=INLATI,KLOEN=ILOEN,PEXWN=Z_EXWN,PEYWN=Z_EYWN,KRESOL=IRESOL)


ALLOCATE(   IESM0(0:IMSMAX))
ALLOCATE(  IDIM0G(0:IMSMAX))

CALL ETRANS_INQ(KGPTOT=IGPTOT,KSPEC=ISPEC,KESM0=IESM0,KDIM0G=IDIM0G)
WRITE(*,*)'IGPTOT',IGPTOT,INLOPA(6),IGPTOTG,ISPEC,ISPEC2G


ALLOCATE(ZGP3(IGPTOT,IMAXLEV,1))

DO JLEV=1,IMAXLEV
  ALLOCATE(ZSPEC1(ISPEC))
  ALLOCATE(ZSPEC3(1,ISPEC))

  CALL FANION(IREP,11,'S',JLEV,'TEMPERATURE', &
     & LLEXIS,LLCOSP,INGRIB,INBITS,ISTRUN,IPUILA)



  CALL FACILE(IREP,11,'S',JLEV,'TEMPERATURE', &
         & ZSPEC1,LLCOSP)
  WRITE(*,*) 'TEMPERATURE LEVEL',JLEV,'READ',IREP
  II=0
  DO JN=0,ISMAX
    DO JM=0,IISMAX(JN)
      ISP=IDIM0G(JM)+4*JN
      II=II+4
      ZSPEC3(1,ISP:ISP+3)=ZSPEC1(II-3:II)
    ENDDO
  ENDDO
  ALLOCATE(ZGP4(IGPTOT,1,1))
  ZGP4(:,:,:)=0.0_JPRB
  IVSETSC=1284442656
  CALL EINV_TRANS(PSPSCALAR=ZSPEC3,PGP=ZGP4)
  DEALLOCATE(ZSPEC1,ZSPEC3)
 
  ALLOCATE(ZGP5(IGPTOT,1,1))
  ZGP5(:,:,:)=0.0_JPRB
  CALL FACILE(IREP,11,'S',JLEV,'HUMI.SPECIFI', &
         & ZGP5,.FALSE.)
  WRITE(*,*) 'HUMI.SPECIFI LEVEL',JLEV,'READ',IREP
  ! convert T,Q to virtual temperature   
  DO II=1,IGPTOT
    ZGP3(II,JLEV,1)=ZGP4(II,1,1)*(1.+0.608_JPRB*ZGP5(II,1,1))
  ENDDO
  DEALLOCATE(ZGP5,ZGP4)
ENDDO
DEALLOCATE(IISMAX,IISNAX)

CALL ECHIEN('CADRE LECTURE   ',ITYPTR,LLMAP,ITRONC,INLATI,INXLON,INLOPA,&
   & ZSINLA,IMAXLEV,ZREF,ZVALH,ZVBH,1,ZEPS,6)

ISMAX =ITRONC
IMSMAX=ITYPTR
WRITE(*,*)'ITRONC,ITYPTR:',ITRONC,ITYPTR
IGPTOTG=INLATI*INXLON
ALLOCATE(IISMAX(0:ISMAX),IISNAX(0:IMSMAX))
CALL ELLIPS(ISMAX,IMSMAX,IISNAX,IISMAX)
ISPEC2G=0
DO J=0,IMSMAX
  ISPEC2G=ISPEC2G+4*(IISNAX(J)+1)
ENDDO

IRESOL=-1

DEALLOCATE(IESM0,IDIM0G)
ALLOCATE(   IESM0(0:IMSMAX))
ALLOCATE(  IDIM0G(0:IMSMAX))

CALL ETRANS_INQ(KGPTOT=IGPTOT,KSPEC=ISPEC,KESM0=IESM0,KDIM0G=IDIM0G)
WRITE(*,*)'IGPTOT',IGPTOT,INLOPA(6),IGPTOTG,ISPEC

CALL FANION(IREP,11,'SURF',0,'PRESSION', &
     & LLEXIS,LLCOSP,INGRIB,INBITS,ISTRUN,IPUILA)
WRITE(*,*) 'SURFPRESSION FANION',IREP

ALLOCATE(ZSPEC2(ISPEC))

CALL FACILE(IREP,11,'SURF',0,'PRESSION',ZSPEC2,LLCOSP)
WRITE(*,*) 'SURFPRESSION READ',IREP
WRITE(*,*) 'ISPEC:',ISPEC
ALLOCATE(ZSPEC3(1,ISPEC))
II=0
DO JN=0,ISMAX
  DO JM=0,IISMAX(JN)
    ISP=IDIM0G(JM)+4*JN
    II=II+4
    ZSPEC3(1,ISP:ISP+3)=ZSPEC2(II-3:II)
  ENDDO
ENDDO
DEALLOCATE(IISMAX,IISNAX)

ALLOCATE(ZGP2(IGPTOT,1,1))
ZGP2(:,:,:)=0.0_JPRB
IVSETSC=1284442656
CALL EINV_TRANS(PSPSCALAR=ZSPEC3,PGP=ZGP2,LDSCDERS=.FALSE.,KPROMA=IGPTOT)
DEALLOCATE(ZSPEC2,ZSPEC3)

! convert ln ps to ps
DO II=1,IGPTOT
  ZGP2(II,1,1)=exp(ZGP2(II,1,1))
ENDDO



CALL ECHIEN('CADRE LECTURE   ',ITYPTR,LLMAP,ITRONC,INLATI,INXLON,INLOPA,&
   & ZSINLA,IMAXLEV,ZREF,ZVALH,ZVBH,1,ZEPS,6)

WRITE(*,*)'ITRONC,ITYPTR:',ITRONC,ITYPTR

ISMAX =ITRONC
IMSMAX=ITYPTR
IGPTOTG=INLATI*INXLON
ALLOCATE(IISMAX(0:ISMAX),IISNAX(0:IMSMAX))
CALL ELLIPS(ISMAX,IMSMAX,IISNAX,IISMAX)
ISPEC2G=0
DO J=0,IMSMAX
  ISPEC2G=ISPEC2G+4*(IISNAX(J)+1)
ENDDO

DEALLOCATE(IESM0,IDIM0G)
ALLOCATE(IESM0(0:IMSMAX))
ALLOCATE(IDIM0G(0:IMSMAX))

CALL ETRANS_INQ(KGPTOT=IGPTOT,KSPEC=ISPEC,KESM0=IESM0,KDIM0G=IDIM0G)
WRITE(*,*)'IGPTOT',IGPTOT,INLOPA(6),IGPTOTG,ISPEC

ALLOCATE(ZSPEC2(ISPEC))
CALL FANION(IREP,11,'SPECSURF',0,'GEOPOTEN', &
     & LLEXIS,LLCOSP,INGRIB,INBITS,ISTRUN,IPUILA)


CALL FACILE(IREP,11,'SPECSURF',0,'GEOPOTEN',ZSPEC2,LLCOSP)
WRITE(*,*) 'SPECSURFGEOPOTEN READ',IREP

ALLOCATE(ZSPEC3(1,ISPEC))
II=0
DO JN=0,ISMAX
  DO JM=0,IISMAX(JN)
    ISP=IDIM0G(JM)+4*JN
    II=II+4
    ZSPEC3(1,ISP:ISP+3)=ZSPEC2(II-3:II)
  ENDDO
ENDDO

DEALLOCATE(IISMAX,IISNAX,IDIM0G)

WRITE(*,*)'ISPEC:',ISPEC

ALLOCATE(ZGP1(IGPTOT,1,1))
ZGP1(:,:,:)=0.0_JPRB
IVSETSC=1284442656
CALL EINV_TRANS(PSPSCALAR=ZSPEC3,PGP=ZGP1,LDSCDERS=.FALSE.,KPROMA=IGPTOT)
DEALLOCATE(ZSPEC2,ZSPEC3)

! geopot to height

DO II=1,IGPTOT
  ZGP1(II,1,1)=ZGP1(II,1,1)/9.8087_JPRB
  !!WRITE(*,*)ZGP1(II,1,1),'geo'
ENDDO

ALLOCATE(ZHEIGHT(IGPTOT,IMAXLEV))

ZHEIGHT=0.0_JPRB

DO JLEV=1,IMAXLEV
  WRITE(*,*)'A,B,level:',ZVALH(JLEV),ZVBH(JLEV),JLEV
ENDDO

ZHEIGHTMEAN=0.0_JPRB
ZPRESSMEAN=0.0_JPRB
ZMAXPRES=0._JPRB
ZMINPRES=999999._JPRB

DO II=1,IGPTOT
  IF(ZGP2(II,1,1)>ZMAXPRES)ZMAXPRES=ZGP2(II,1,1)
  IF(ZGP2(II,1,1)<ZMINPRES)ZMINPRES=ZGP2(II,1,1)
  ZPRESSMEAN=ZPRESSMEAN+ZGP2(II,1,1)
  ZHEIGHTMEAN=ZHEIGHTMEAN+ZGP1(II,1,1)
  ZHEIGHT(II,IMAXLEV)=ZGP1(II,1,1)+(ZGP2(II,1,1)-ZVALH(IMAXLEV)*ZPREF-ZVBH(IMAXLEV)*ZGP2(II,1,1))/ &
 & ((ZGP2(II,1,1)+ZVALH(IMAXLEV)*ZPREF+ZVBH(IMAXLEV)*ZGP2(II,1,1))*0.5_JPRB)*ZGASCONST/ZGRAVITY* &
 &  ZGP3(II,IMAXLEV,1)

  DO JLEV=IMAXLEV-1,1,-1
    ZHEIGHT(II,JLEV)=ZHEIGHT(II,JLEV+1)+((ZVALH(JLEV+1)-ZVALH(JLEV))*ZPREF+(ZVBH(JLEV+1)-ZVBH(JLEV))* &
 & ZGP2(II,1,1))/((ZVALH(JLEV+1)+ZVALH(JLEV))*ZPREF*0.5_JPRB+(ZVBH(JLEV+1)+ZVBH(JLEV))*ZGP2(II,1,1)*0.5_JPRB) &
 & *ZGASCONST/ZGRAVITY*(ZGP3(II,JLEV+1,1)+ZGP3(II,JLEV,1))*0.5_JPRB
  ENDDO
ENDDO
WRITE(*,*),'ZMAXPRES',ZMAXPRES,'ZMINPRES',ZMINPRES
DEALLOCATE(ZGP3,ZGP1)
ALLOCATE(ZHEIGHT2D(IGPTOT))
ALLOCATE(ZDIST2D(IGPTOT))
ALLOCATE(ZREFL2D(IGPTOT))
ZREFL2D(:)=-999.99_JPRB
ZDIST2D(:)=999999.99_JPRB
IF(IGPTOT>0) ZHEIGHTMEAN=ZHEIGHTMEAN/IGPTOT
IF(IGPTOT>0) ZPRESSMEAN=ZPRESSMEAN/IGPTOT
WRITE(*,*)'mean height of level,level:',ZHEIGHTMEAN,'SURFACE',ZPRESSMEAN
JREP=0
DO JLEV=1,IMAXLEV
  ZHEIGHTMEAN=0.0_JPRB
  ZPRESSMEAN=0.0_JPRB
  DO II=1,IGPTOT
    ZHEIGHT2D(II)=ZHEIGHT(II,JLEV)
    !!WRITE(*,*)'height2d',ZHEIGHT2D(II),II
    ZHEIGHTMEAN=ZHEIGHTMEAN+ZHEIGHT(II,JLEV)
    ZPRESSMEAN=ZPRESSMEAN+ZVALH(JLEV)*ZPREF+ZVBH(JLEV)*ZGP2(II,1,1)
  ENDDO
  IF(IGPTOT>0) ZHEIGHTMEAN=ZHEIGHTMEAN/IGPTOT
  IF(IGPTOT>0) ZPRESSMEAN=ZPRESSMEAN/IGPTOT
  WRITE(*,*)'mean height of level,level:',ZHEIGHTMEAN,JLEV,ZPRESSMEAN
  CALL FAIENC(IREP,11,'S   ',JLEV,'CLOUD_WATER',ZHEIGHT2D,.FALSE.)
  JREP=IREP+JREP
  WRITE(*,*)IREP
  
  CALL FAIENC(IREP,11,'S   ',JLEV,'RAIN',ZREFL2D,.FALSE.)
  JREP=IREP+JREP
  WRITE(*,*)IREP

  IF(JREP>0)THEN
    WRITE(*,*)'coding field to FA file failed!',JREP
    CALL ABOR1('coding field to FA file failed!')
  ENDIF
  CALL FAIENC(IREP,11,'S   ',JLEV,'SNOW',ZDIST2D,.FALSE.)
  JREP=IREP+JREP
  IF(JREP>0)THEN
    WRITE(*,*)'coding field to FA file failed!',JREP
    CALL ABOR1('coding field to FA file failed!')
  ENDIF
ENDDO
DEALLOCATE(ZHEIGHT,ZHEIGHT2D,ZGP2,ZREFL2D,ZDIST2D,ZVALH,ZVBH)
!**************************************

CALL FAIRME(IREP,11,'KEEP')
IF (IREP /= 0) THEN
  WRITE(*,*)'CLOSING FA FILE FAILED - ERROR CODE:',IREP
  CALL ABOR1('CLOSING FA FILE FAILED')
ENDIF
WRITE(*,*) 'ALL FILES ARE CLOSED - PROGRAM FINISHED'
IF (LHOOK) CALL DR_HOOK('HEIGHTTOMOD',1,ZHOOK_HANDLE)

END PROGRAM HEIGHTTOMOD
